# Generated by Django 4.2.2 on 2023-06-24 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_chattext_remove_cartitem_cart_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chattext',
            name='time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
