# Generated by Django 4.2.2 on 2023-06-24 03:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('my_app', '0004_chattext_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chattext',
            name='reciver',
        ),
        migrations.AddField(
            model_name='chattext',
            name='receiver',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
